version: '3'

services:
  nextjs:
    container_name: boardlife_nextjs
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - '3001'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://boardlife.teeroz.net
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - network
      - infra_infra-local

# nginx:
#   image: nginx:alpine
#   restart: always
#   ports:
#     - '80:80'
#     - '443:443'
#   volumes:
#     - ./nginx/conf.d:/etc/nginx/conf.d
#     - ./nginx/certs:/etc/nginx/certs
#     - ./nginx/logs:/var/log/nginx
#     - /etc/letsencrypt:/etc/letsencrypt:ro
#   networks:
#     - network
#   depends_on:
#     - nextjs

networks:
  network:
    driver: bridge
  infra_infra-local:
    external: true 